version: '2'
services:
    purecloud-app:
        image: purecloud
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://purecloud-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=PureCloud
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    purecloud-mongodb:
        extends:
            file: mongodb.yml
            service: purecloud-mongodb
